#!/bin/bash

keyboard=$(libinput list-devices | grep keyboard -B4 | grep -E "keyboard$" -A1 | grep -o '/dev/input/event[1-9]*')
event_type=EV_KEY
action_type=POINTER_BUTTON
pressed="pressed,"

readarray -t devices <<<$(libinput list-devices | grep "Capabilities:     pointer $" -B4 | grep -o '/dev/input/event[0-9]*')

# COMMANDS MAP
BTN_EXTRA=(KEY_LEFTMETA KEY_PAGEUP)
BTN_SIDE=(KEY_LEFTMETA KEY_PAGEDOWN)

function press() {
    evemu-event ${keyboard} --sync --type EV_KEY --code $1 --value 1;
}

function release() {
    evemu-event ${keyboard} --sync --type EV_KEY --code $1 --value 0;    
}

function wsNext(){
    # Press
    press KEY_LEFTCTRL; press KEY_LEFTALT; press KEY_RIGHT;
    # Release
    release KEY_RIGHT; release KEY_LEFTALT; release KEY_LEFTCTRL;
}

function wsPrev(){
    # Press
    press KEY_LEFTCTRL; press KEY_LEFTALT; press KEY_LEFT;
    # Release
    release KEY_LEFT; release KEY_LEFTALT; release KEY_LEFTCTRL;
}


function pressKey(){
    device=$1; key=$2; value=$3
    # echo "pressing ${key} ${value}"
    # evemu-event ${keyboard} --sync --type ${event_type} --code ${key} --value ${value};

    if [ $key == "KEY_PAGEUP" ] && [ $value == "1" ]; then
        wsNext
    fi

    if [ $key == "KEY_PAGEDOWN" ] && [ $value == "1" ]; then
        wsPrev
    fi

}

function pressCommand(){
    device=$1; button=$2; movement=$3
    var=$button[@]
    command=${!var}

    if [ ${movement} = ${pressed} ]; then
        for key in ${command}; do
            pressKey ${device} ${key} 1
        done
    else
        for key in ${command}; do
            pressKey ${device} ${key} 0
        done | tac
    fi
}

function parseEventLine(){
    device=$1
    action=$2
    button=$4
    movement=$6

    # compute only if right action
    if [ ${action} = ${action_type} ]; then
        pressCommand ${device} ${button} ${movement}
    fi
}

function mapDevice(){
    device=$1
    while read line; do
        parseEventLine ${line}
    done < <(stdbuf -oL libinput debug-events --device ${device} & )
}

if [[ ${devices[0]} == '' ]]; then
  echo "No Pointers Found. Try again."
  exit 1
fi

for device in ${devices[@]}; do
    ( mapDevice ${device} ) &
done

wait
